import os

def fix_sanctions():
    path = r'd:\learning\aml\db\sanctions_data.sql'
    header = """SET client_encoding = 'UTF8';
-- KINETIX PLATFORM: Mock Sanctions List Data (OFAC SDN Style)
-- 200 Mock Records for Testing Sanctions Screening

CREATE TABLE IF NOT EXISTS client_onboarding.sanctions_list (
    id SERIAL PRIMARY KEY,
    entity_name VARCHAR(255) NOT NULL,
    entity_type VARCHAR(50) NOT NULL, -- INDIVIDUAL, ENTITY, VESSEL, AIRCRAFT
    program VARCHAR(100) NOT NULL,    -- e.g., RUSSIA, IRAN, SDGT
    list_type VARCHAR(50) NOT NULL,   -- SDN, NON-SDN
    country VARCHAR(100),
    entity_address TEXT,              -- Physical or registered address
    tax_id VARCHAR(50),               -- SSN, EIN, or National ID (New)
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO client_onboarding.sanctions_list (entity_name, entity_type, program, list_type, country, entity_address, tax_id, remarks) VALUES
"""
    rows = [
        # RUSSIA
        "('VTB Bank PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '12 Presnenskaya Naberezhnaya, Moscow', 'RU-INN-7702000225', 'Major state-owned bank')",
        "('Sberbank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '19 Vavilova St, Moscow', 'RU-INN-7707083893', 'Russian financial services giant')",
        "('Gazprombank PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '16 Nametkina St, Moscow', 'RU-INN-7703230494', 'Energy sector financial arm')",
        "('Alfa-Bank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '27 Kalanchyovskaya St, Moscow', 'RU-INN-7701101', 'Private commercial bank')",
        "('Promsvyazbank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '10 Smirnovskaya St, Moscow', 'RU-INN-7705141011', 'Defense sector bank')",
        "('Alisher Usmanov', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Rublyovksy Highway, Moscow', NULL, 'Oligarch, metals and tech')",
        "('Roman Abramovich', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Tsvetnoy Blvd, Moscow', NULL, 'Prominent businessman')",
        "('Igor Sechin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Sofiyskaya Naberezhnaya, Moscow', NULL, 'CEO of Rosneft')",
        "('Alexey Miller', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Nametkina St, Moscow', NULL, 'CEO of Gazprom')",
        "('Gennady Timchenko', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Geneva, Switzerland (Primary Res)', NULL, 'Volga Group founder')",
        "('Rosneft Oil Company', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '26/1 Sofiyskaya Naberezhnaya, Moscow', NULL, 'State oil major')",
        "('Gazprom PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '16 Nametkina St, Moscow', NULL, 'State gas giant')",
        "('Rostec', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '24 Usacheva St, Moscow', NULL, 'State defense conglomerate')",
        "('United Shipbuilding Corporation', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '11 Maroseyka St, Moscow', NULL, 'Naval construction')",
        "('Sukhoi Aviation', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '23B Polikarpov St, Moscow', NULL, 'Aircraft manufacturer')",
        "('Kalashnikov Concern', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '3 Deryabin Prospekt, Izhevsk', NULL, 'Small arms manufacturer')",
        "('Bank Rossiya', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '2 Rastrelli Square, St. Petersburg', NULL, 'St. Petersburg based bank')",
        "('SMP Bank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Sadovnicheskaya St, Moscow', NULL, 'Rotenberg-controlled bank')",
        "('Uralvagonzavod', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '28 Vostochnoye Highway, Nizhny Tagil', 'RU-INN-6623029175', 'Tank manufacturer')",
        "('Wagner Group', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Molkino, Krasnodar Krai', 'RU-TAX-WAGNER66', 'Private military company')",
        "('Yevgeny Prigozhin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'St. Petersburg, Russia', 'RU-ID-99887766', 'Wagner founder')",
        "('Sergei Roldugin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Mariinsky Theatre, St. Petersburg', NULL, 'Cellist, associate of leadership')",
        "('Arkady Rotenberg', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', NULL, 'Infrastructure tycoon')",
        "('Boris Rotenberg', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', NULL, 'Co-owner of SMP Bank')",
        "('Nikolai Patrushev', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Kremlin, Moscow', NULL, 'Security Council Secretary')",
        "('Alexander Bortnikov', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Lubyanka Sq, Moscow', NULL, 'FSB Director')",
        "('Sergei Naryshkin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Yasenovo, Moscow', NULL, 'SVR Director')",
        "('Yuri Kovalchuk', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'St. Petersburg, Russia', NULL, 'Bank Rossiya chairman')",
        "('Oleg Deripaska', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'London/Moscow', NULL, 'En+ Group founder')",
        "('Viktor Vekselberg', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', NULL, 'Renova Group owner')",
        "('United Energy Systems', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Kitaigorodsky Proyezd, Moscow', NULL, 'Electricity grids')",
        "('Aeroflot PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Arbat St, Moscow', NULL, 'Flag carrier')",
        "('Russian Railways (RZD)', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Novaya Basmannaya, Moscow', NULL, 'State rail operator')",
        "('Transneft', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Polyanka St, Moscow', NULL, 'Oil pipeline monopoly')",
        "('Alrosa PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Mirny, Sakha Republic', NULL, 'Diamond mining major')",
        "('Sovcombank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Kostroma, Russia', NULL, 'Universal commercial bank')",
        "('Novatek PAO', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Tarkosale, Yamalo-Nenets', NULL, 'LNG producer')",
        "('Norilsk Nickel', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '1st Krasnogvardeyskiy Proyezd, Moscow', NULL, 'Nickel and palladium producer')",
        "('Militia Forces of DNR', 'ENTITY', 'UKRAINE-EO13660', 'SDN', 'Ukraine/Russia', 'Donetsk, Ukraine', NULL, 'Armed group in East Ukraine')",
        "('Militia Forces of LNR', 'ENTITY', 'UKRAINE-EO13660', 'SDN', 'Ukraine/Russia', 'Luhansk, Ukraine', NULL, 'Armed group in East Ukraine')",
        "('Zelenograd Scientific Center', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Georgievsky Prospekt, Zelenograd', NULL, 'Microelectronics research')",
        "('Baikal Electronics', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', NULL, 'Processor designer')",
        "('Mikron', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '10 Akademika Valli St, Zelenograd', NULL, 'Semiconductor manufacturer')",
        "('MCST', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Nagatinskaya St, Moscow', NULL, 'Elbrus processor developer')",
        "('T-Platforms', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', NULL, 'Supercomputer manufacturer')",
        "('Radio-Electronic Technologies (KRET)', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Goncharnaya St, Moscow', NULL, 'Avionics manufacturer')",
        "('High Precision Systems', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Leningradsky Prospekt, Moscow', NULL, 'Missile systems')",
        "('Tactical Missiles Corporation', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Korolev, Moscow Oblast', NULL, 'Weapon systems')",
        "('Russian Direct Investment Fund (RDIF)', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Vozdvizhenka St, Moscow', NULL, 'Sovereign wealth fund')",
        "('VEB.RF', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Academician Sakharov Ave, Moscow', NULL, 'Development bank')",
        "('Novikombank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Polyanka St, Moscow', NULL, 'Rostec-owned bank')",
        "('Bank Otkritie', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Letnikovskaya St, Moscow', NULL, 'Major retail bank')",
        "('Credit Bank of Moscow', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Lukov Ln, Moscow', NULL, 'Commercial bank')",
        "('Rosselkhozbank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Olkhovskaya St, Moscow', NULL, 'Agricultural bank')",
        "('Stroytransgaz', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Arbat St, Moscow', NULL, 'Infrastructure construction')",
        "('Stroygazmontazh', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Vavilova St, Moscow', NULL, 'Energy construction')",
        "('Mostotrest', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Barklaya St, Moscow', NULL, 'Bridge construction')",
        "('Uran-9', 'VESSEL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moored at Sevastopol', NULL, 'Autonomous naval system')",
        "('Admiral Kuznetsov', 'VESSEL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Severomorsk Naval Base', NULL, 'Aircraft carrier')",
        "('Moskva', 'VESSEL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Sunk (formerly Sevastopol)', NULL, 'Missile cruiser')",
        # IRAN
        "('Central Bank of Iran', 'ENTITY', 'IRAN', 'SDN', 'Iran', '144 Mirdamad Blvd, Tehran', NULL, 'Central financial regulator')",
        "('Bank Melli Iran', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Ferdowsi Ave, Tehran', NULL, 'Commercial bank')",
        "('Bank Mellat', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Valiasr Ave, Tehran', NULL, 'Commercial bank')",
        "('Bank Sepah', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Saeid Sq, Tehran', NULL, 'Military-linked bank')",
        "('Parsian Bank', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Argentina Sq, Tehran', NULL, 'Private bank')",
        "('Pasargad Bank', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Mirdamad Blvd, Tehran', NULL, 'Private bank')",
        "('Islamic Revolutionary Guard Corps (IRGC)', 'ENTITY', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran (Multiple HQ)', NULL, 'Elite military force')",
        "('Quds Force', 'ENTITY', 'SDGT', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'IRGC external operations')",
        "('Ebrahim Raisi', 'INDIVIDUAL', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Political leadership')",
        "('Ali Khamenei', 'INDIVIDUAL', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Supreme Leader')",
        "('Mohammad Javad Zarif', 'INDIVIDUAL', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Former Foreign Minister')",
        "('Qasem Soleimani', 'INDIVIDUAL', 'SDGT', 'SDN', 'Iran', 'Kerman, Iran (Gravesite)', NULL, 'Deceased Quds Force commander')",
        "('National Iranian Oil Company (NIOC)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Taleghani Ave, Tehran', NULL, 'State oil company')",
        "('National Iranian Tanker Company (NITC)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Atefi St, Tehran', NULL, 'Oil shipping')",
        "('Islamic Republic of Iran Shipping Lines (IRISL)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Aseman Tower, Tehran', NULL, 'National shipping line')",
        "('Atomic Energy Organization of Iran (AEOI)', 'ENTITY', 'NPWMD', 'SDN', 'Iran', 'Kargar Ave, Tehran', NULL, 'Nuclear program lead')",
        "('Mahan Air', 'ENTITY', 'SDGT', 'SDN', 'Iran', 'Mahan Tower, Tehran', NULL, 'Commercial airline')",
        "('Iran Air', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Mehrabad Airport, Tehran', NULL, 'Flag carrier')",
        "('Petrochemical Commercial Company (PCC)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Vanak Sq, Tehran', 'IR-TAX-PCC44', 'Petrochemical exports')",
        "('Persia Cargo', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kish Island, Iran', 'IR-TAX-445566', 'Logistics')",
        "('Abadan Refinery', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Abadan, Khuzestan', NULL, 'Oil refining')",
        "('Kharg Island Loading', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kharg Island, Persian Gulf', NULL, 'Strategic oil port')",
        "('Iranian Offshore Oil Company', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Offshore production')",
        "('Mapna Group', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Mirdamad Blvd, Tehran', NULL, 'Energy infrastructure')",
        "('Saipa Motor', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kilometer 15 Karaj Rd, Tehran', NULL, 'Automotive manufacturer')",
        "('Iran Khodro', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kilometer 14 Karaj Rd, Tehran', NULL, 'Automotive manufacturer')",
        "('Shahid Hemmat Industrial Group', 'ENTITY', 'NPWMD', 'SDN', 'Iran', 'Parchin, Iran', NULL, 'Ballistic missile program')",
        "('Shahid Bakeri Industrial Group', 'ENTITY', 'NPWMD', 'SDN', 'Iran', 'Khojir, Iran', NULL, 'Ballistic missile program')",
        "('Defense Industries Organization', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Pasdaran St, Tehran', NULL, 'Military production')",
        "('Khatam al-Anbiya', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'IRGC construction arm')",
        "('Execution of Imam Khomeini''s Order (EIKO)', 'ENTITY', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Parastatal conglomerate')",
        "('Mostazafan Foundation', 'ENTITY', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Bonyad conglomerate')",
        "('Bank Saderat Iran', 'ENTITY', 'SDGT', 'SDN', 'Iran', 'Somayeh St, Tehran', NULL, 'Involved in terrorism financing')",
        "('Future Bank B.S.C.', 'ENTITY', 'IRAN', 'SDN', 'Bahrain/Iran', 'Manama, Bahrain', NULL, 'Joint venture bank')",
        "('Persia International Bank PLC', 'ENTITY', 'IRAN', 'SDN', 'UK/Iran', '6-8 Lothbury, London', NULL, 'London-based subsidiary')",
        "('EIKO Wealth Management', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', NULL, 'Financial arm')",
        "('Saman Bank', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Valiasr Ave, Tehran', NULL, 'Commercial bank')",
        "('Tehran Stock Exchange', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Hafez St, Tehran', NULL, 'Capital markets')",
        "('Kish Protection and Indemnity', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kish Island, Iran', NULL, 'Maritime insurance')",
        "('Bimeh Iran', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Fatemi St, Tehran', NULL, 'State insurance')",
        # NORTH KOREA
        "('Foreign Trade Bank of DPRK', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Jungsong-dong, Pyongyang', NULL, 'Main foreign exchange bank')",
        "('Korea Kwangson Banking Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Financial operations')",
        "('Kim Jong Un', 'INDIVIDUAL', 'DPRK', 'SDN', 'North Korea', 'Ryongsong Residence, Pyongyang', NULL, 'Supreme Leader')",
        "('Kim Yo Jong', 'INDIVIDUAL', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Political leadership')",
        "('Lazarus Group', 'ENTITY', 'CYBER-DPRK', 'SDN', 'North Korea', 'Potonggang District, Pyongyang', NULL, 'Cyber warfare unit')",
        "('Koryo Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'State bank')",
        "('Daedong Credit Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Joint venture bank')",
        "('Mansudae Overseas Projects', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Overseas construction')",
        "('Air Koryo', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Sunan Airport, Pyongyang', NULL, 'State airline')",
        "('Kaesong Industrial Complex', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Kaesong, NK', NULL, 'Economic zone')",
        "('Namchongang Trading Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Nuclear procurement')",
        "('Korea Mining Development Trading Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Arms exports')",
        "('Choson Expo', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Software development')",
        "('Ryugyong Hotel Trust', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Hospitality')",
        "('DPRK Merchant Marine', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Shipping coordination')",
        "('Mu Bong 1', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Anchored at Nampo', NULL, 'Cargo ship')",
        "('Hui Chon', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Nampo Port', NULL, 'Container vessel')",
        "('Jang Ja San Ho', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Wonsan Port', NULL, 'Bulk carrier')",
        "('O Ryong', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Hungnam Port', NULL, 'Oil tanker')",
        "('Po Thong Gang', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Pyongyang Port', NULL, 'General cargo')",
        "('Ryong Gun Bong', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Nampo Port', NULL, 'General cargo')",
        "('Tangun Trading Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Advanced technology')",
        "('Green Pine Associated Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Wonsan, NK', NULL, 'Maritime intelligence')",
        "('Lab 110', 'ENTITY', 'CYBER-DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Reconnaissance General Bureau')",
        "('Chosun United Development Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Capital investment')",
        "('Amroggang Development Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Currency operations')",
        "('Korea Computer Center', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'IT development')",
        "('Red Star OS', 'ENTITY', 'CYBER-DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'State operating system')",
        "('Pan Systems Pyongyang', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', NULL, 'Electronics trade')",
        "('Haegeumgang Resort', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Mt Kumgang', NULL, 'Tourism assets')",
        # SYRIA
        "('Central Bank of Syria', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Altajhiz St, Damascus', NULL, 'Monetary authority')",
        "('Commercial Bank of Syria', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Yousef Al-Azmeh Sq, Damascus', NULL, 'Largest state bank')",
        "('Bashar al-Assad', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Presidential Palace, Damascus', NULL, 'President')",
        "('Asma al-Assad', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', NULL, 'First Lady')",
        "('Syrian Arab Airlines', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus Int Airport', NULL, 'Flag carrier')",
        "('Cham Wings Airlines', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus Tower Bldg', NULL, 'Private airline')",
        "('Syrian Petroleum Company', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Dummar, Damascus', NULL, 'State energy')",
        "('Mahrukat', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', NULL, 'Fuel distribution')",
        "('Baniyas Refinery', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Baniyas, Tartus', NULL, 'Oil refinement')",
        "('Homs Refinery', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Homs, Syria', NULL, 'Oil refinement')",
        "('Military Intelligence Directorate', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Kafar Souseh, Damascus', NULL, 'Security apparatus')",
        "('Tiger Forces', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Latakia, Syria', NULL, 'Elite military unit')",
        "('Rami Makhlouf', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', NULL, 'Tycoon, associate of leadership')",
        "('Al-Watan Newspaper', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', NULL, 'State-linked media')",
        "('Syrian Scientific Studies and Research Center', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Barzah, Damascus', NULL, 'Chemical weapons research')",
        "('Mediterranean Shipping Agency', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Tartus Port, Syria', NULL, 'Maritime logistics')",
        "('Latakia Port Authority', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Latakia Port, Syria', NULL, 'Major seaport')",
        "('Tartus Port Management', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Tartus Port, Syria', NULL, 'Strategic port')",
        "('Maher al-Assad', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', NULL, 'Military commander')",
        "('Syriatel', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Mazzeh Highway, Damascus', NULL, 'Telecom provider')",
        # VENEZUELA
        "('Petroleos de Venezuela, S.A. (PDVSA)', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Libertador, Caracas', NULL, 'State oil company')",
        "('Nicolas Maduro', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Palacio de Miraflores, Caracas', NULL, 'President')",
        "('Diosdado Cabello', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Caracas, Venezuela', NULL, 'Political leadership')",
        "('Cilia Flores', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Caracas, Venezuela', NULL, 'Political leadership')",
        "('Delcy Rodriguez', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Caracas, Venezuela', NULL, 'Vice President')",
        "('Tareck El Aissami', 'INDIVIDUAL', 'NARCO-VENEZUELA', 'SDN', 'Venezuela', 'Caracas, Venezuela', NULL, 'Former Petroleum Minister')",
        "('Central Bank of Venezuela', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Urdaneta, Caracas', NULL, 'Monetary authority')",
        "('BANDES', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Universidad, Caracas', NULL, 'Economic development bank')",
        "('Banco de Venezuela', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Universidad, Caracas', NULL, 'State-owned bank')",
        "('CVG Fundicion', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Puerto Ordaz, Bolivar', NULL, 'Gold/Mining sector')",
        "('Minerven', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'El Callao, Bolivar', NULL, 'State gold mining')",
        "('Alex Saab', 'INDIVIDUAL', 'VENEZUELA-EO13850', 'SDN', 'Colombia/Venezuela', 'Barranquilla, Colombia', NULL, 'Corruption/Money laundering')",
        "('Citgo Petroleum (US blocked)', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'USA/Venezuela', '1293 Eldridge Pkwy, Houston, TX', NULL, 'Refining subsidiary')",
        "('Conviasa', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Maiquetia Airport, Vargas', NULL, 'State airline')",
        "('SEBIN', 'ENTITY', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'El Helicoide, Caracas', NULL, 'Intelligence agency')",
        "('DGCIM', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Boleita, Caracas', NULL, 'Military counterintelligence')",
        "('National Electoral Council (CNE)', 'ENTITY', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Plaza Caracas, Caracas', NULL, 'Electoral authority')",
        "('Supreme Tribunal of Justice (TSJ)', 'ENTITY', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Av Baralt, Caracas', NULL, 'Judiciary')",
        "('Pante Pente', 'VESSEL', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Jose Terminal, Anzoategui', NULL, 'Oil tanker')",
        "('Sandino', 'VESSEL', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Puerto La Cruz', NULL, 'Oil tanker')",
        # OTHERS
        "('Alexander Lukashenko', 'INDIVIDUAL', 'BELARUS', 'SDN', 'Belarus', 'Independence Palace, Minsk', NULL, 'President')",
        "('Belaruskali', 'ENTITY', 'BELARUS', 'SDN', 'Belarus', 'Soligorsk, Belarus', NULL, 'Potash producer')",
        "('Belintertrans', 'ENTITY', 'BELARUS', 'SDN', 'Belarus', 'Oktyabrskaya St, Minsk', NULL, 'Logistics')",
        "('Cubaexport', 'ENTITY', 'CUBA', 'SDN', 'Cuba', 'Calle 23, Havana', NULL, 'State export agency')",
        "('Banco Central de Cuba', 'ENTITY', 'CUBA', 'SDN', 'Cuba', 'Havana, Cuba', NULL, 'Central bank')",
        "('Miguel Diaz-Canel', 'INDIVIDUAL', 'CUBA', 'SDN', 'Cuba', 'Palace of the Revolution, Havana', NULL, 'President')",
        "('Houthis / Ansar Allah', 'ENTITY', 'SDGT', 'SDN', 'Yemen', 'Sana''a, Yemen', NULL, 'Armed group')",
        "('Abdul-Malik al-Houthi', 'INDIVIDUAL', 'SDGT', 'SDN', 'Yemen', 'Saada, Yemen', NULL, 'Houthi leader')",
        "('Myanmar Economic Holdings', 'ENTITY', 'MYANMAR-EO14014', 'SDN', 'Myanmar', 'Nay Pyi Taw, Myanmar', NULL, 'Military conglomerate')",
        "('Min Aung Hlaing', 'INDIVIDUAL', 'MYANMAR-EO14014', 'SDN', 'Myanmar', 'Nay Pyi Taw, Myanmar', NULL, 'Military leader')",
        "('Zimbabwe Mining Development Corp', 'ENTITY', 'ZIMBABWE', 'SDN', 'Zimbabwe', 'Harare, Zimbabwe', NULL, 'Mineral extraction')",
        "('Emmerson Mnangagwa', 'INDIVIDUAL', 'ZIMBABWE', 'SDN', 'Zimbabwe', 'State House, Harare', NULL, 'President')",
        "('Hezbollah', 'ENTITY', 'SDGT', 'SDN', 'Lebanon', 'Dahieh, Beirut', NULL, 'Armed group / Political party')",
        "('Hassan Nasrallah', 'INDIVIDUAL', 'SDGT', 'SDN', 'Lebanon', 'Beirut, Lebanon', NULL, 'Hezbollah Secretary General')",
        "('Al-Shabaab', 'ENTITY', 'SDGT', 'SDN', 'Somalia', 'Jilib, Somalia', NULL, 'Terrorist group')",
        "('Cartel de Jalisco Nueva Generacion', 'ENTITY', 'NARCO', 'SDN', 'Mexico', 'Jalisco, Mexico', NULL, 'Drug cartel')",
        "('El Mencho', 'INDIVIDUAL', 'NARCO', 'SDN', 'Mexico', 'Unknown, Mexico', NULL, 'Cartel leader')",
        "('Sinatra Oil Tanker', 'VESSEL', 'SDGT', 'SDN', 'Panama/Iran', 'Persian Gulf', NULL, 'Oil transport for sanctioned groups')",
        "('Air Zimbabwe (Gated)', 'ENTITY', 'ZIMBABWE', 'SDN', 'Zimbabwe', 'Harare Airport', NULL, 'Aviation')",
        "('Belarusian Oil Co', 'ENTITY', 'BELARUS', 'SDN', 'Belarus', 'Mozyr, Belarus', NULL, 'Oil trade')",
        "('Hamas', 'ENTITY', 'SDGT', 'SDN', 'Gaza', 'Gaza City', NULL, 'Terrorist group')",
        "('Ismail Haniyeh', 'INDIVIDUAL', 'SDGT', 'SDN', 'Gaza/Qatar', 'Doha, Qatar', NULL, 'Political leader')",
        "('Islamic State (ISIS)', 'ENTITY', 'SDGT', 'SDN', 'Global', 'Varies (Syria/Iraq)', NULL, 'Terrorist organization')",
        "('Al-Qaeda', 'ENTITY', 'SDGT', 'SDN', 'Global', 'Varies (Pakistan/Yemen)', NULL, 'Terrorist organization')",
        "('Taliban', 'ENTITY', 'SDGT', 'SDN', 'Afghanistan', 'Kabul, Afghanistan', NULL, 'Governing group')",
        "('Haibatullah Akhundzada', 'INDIVIDUAL', 'SDGT', 'SDN', 'Afghanistan', 'Kandahar, Afghanistan', NULL, 'Taliban leader')",
        "('Sudan People''s Liberation Movement', 'ENTITY', 'SUDAN-EO13664', 'SDN', 'South Sudan', 'Juba, South Sudan', NULL, 'Armed conflict party')",
        "('Fuerzas Armadas Revolucionarias de Colombia', 'ENTITY', 'SDGT', 'SDN', 'Colombia', 'Varies (Border regions)', NULL, 'FARC dissident groups')",
        "('Los Zetas', 'ENTITY', 'NARCO', 'SDN', 'Mexico', 'Tamaulipas, Mexico', NULL, 'Criminal organization')",
        "('Sinaloa Cartel', 'ENTITY', 'NARCO', 'SDN', 'Mexico', 'Sinaloa, Mexico', NULL, 'Criminal organization')"
    ]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(",\n".join(rows) + ";\n")

def fix_aml():
    path = r'd:\learning\aml\db\aml_mock_data.sql'
    content = """-- KINETIX PLATFORM: AML Onboarding Mock Data
-- 200 Records covering Clean, Sanctioned, Unverified, and High-Risk scenarios

-- SCENARIO 1: CLEAN PASS (80 Records)
INSERT INTO client_onboarding.onboarding_details (
    company_name, company_address, country, lei_identifier, entity_type, 
    business_activity, source_of_funds, expected_volume, status,
    dba_name, ein_number, routing_number, account_number, mcc_code
) VALUES
('Evergreen Financial Group', '120 Wall Street, New York, NY 10005', 'United States', '5493001KJY7UW9K12345', 'Bank', 'Investment Banking', 'Operating Revenues', '$10M - $100M', 'PENDING_REVIEW', 'Evergreen Private Wealth', '12-3456789', '021000021', '9988776655', '6011'),
('North Star Asset Management', '10 Collyer Quay, Ocean Financial Centre', 'Singapore', '5493002KJY7UW9K67890', 'Fund', 'Asset Management', 'Investment Returns', '$100M+', 'PENDING_REVIEW', 'North Star Funds', 'SG-99-887766', 'OCBCSGSG', '123-456-789-0', '6211'),
('Riverbank Global Trade', 'Canary Wharf, London E14 5AB', 'United Kingdom', '5493003KJY7UW9K11111', 'Corporate', 'Fintech / Payments', 'Operating Revenues', '$1M - $10M', 'PENDING_REVIEW', 'Riverbank FX', 'UK-77-665544', '40-05-30', '88776655', '4722'),
('Indus Valley Ventures', 'Bandra Kurla Complex, Mumbai, MH 400051', 'India', '5493004KJY7UW9K22222', 'Broker-Dealer', 'Investment Banking', 'Shareholder Capital', '$1M - $10M', 'PENDING_REVIEW', 'Indus Valley Investments', 'AAACI-1234-A', 'SBIN0000300', '300400500600', '6211'),
('Alpine Wealth Systems', 'Bahnhofstrasse 45, Zurich', 'Switzerland', '5493006KJY7UW9K44444', 'Bank', 'Retail Banking', 'Investment Returns', '$10M - $100M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Sakura Trade Corp', '1-1-2 Otemachi, Chiyoda-ku, Tokyo', 'Japan', '5493007KJY7UW9K55555', 'Corporate', 'Energy / Commodities', 'Operating Revenues', '$10M - $100M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Maple Leaf Capital', 'Bay Street, Toronto, ON M5J 2R8', 'Canada', '5493008KJY7UW9K66666', 'Fund', 'Asset Management', 'Investment Returns', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Sydney Harbour Trust', 'George Street, Sydney, NSW 2000', 'Australia', '5493009KJY7UW9K77777', 'Bank', 'Investment Banking', 'Operating Revenues', '$1M - $10M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Frankfurt Deutsche Handels', 'Mainzer Landstrasse, Frankfurt', 'Germany', '5493010KJY7UW9K88888', 'Broker-Dealer', 'Investment Banking', 'Shareholder Capital', '$1M - $10M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Pacific Rim Equities', 'Marina Bay Financial Centre, Tower 1', 'Singapore', '5493012KJY7UW9K00000', 'Fund', 'Asset Management', 'Investment Returns', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Thames River Clearing', 'Lombard Street, London EC3V 9AA', 'United Kingdom', '5493013KJY7UW9K12121', 'Bank', 'Retail Banking', 'Operating Revenues', '$10M - $100M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Dubai Pearl Realty', 'Palm Jumeirah', 'United Arab Emirates', '5493035KJY7UW9V77883', 'Other', 'Real Estate', 'Operating Revenues', '$1M - $10M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('VTB Bank PJSC', '12 Presnenskaya Naberezhnaya, Moscow', 'Russia', '5493060XVTBBANK88990', 'Bank', 'Investment Banking', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', 'VTB Private', 'RU-INN-7702000225', 'VTB-RU-MS', '1122334455', '6011'),
('Sberbank', '19 Vavilova St, Moscow', 'Russia', '5493061XSBERBANK1122', 'Bank', 'Retail Banking', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', 'Sber Retail', 'RU-INN-7707083893', 'SBER-RU-MS', '5544332211', '6011'),
('Wagner Group', 'Molkino, Krasnodar Krai', 'Russia', '5493062XWAGNER4455', 'Other', 'Other', 'Other', '$10M - $100M', 'PENDING_REVIEW', 'Shield Security', 'RU-INV-990088', 'WAGNER-RU', '0000000000', '7393'),
('Al-Qaeda', 'Varies (Pakistan/Yemen)', 'Global', '5493063XALQAEDA0099', 'Other', 'Other', 'Other', '< $1M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Hamas', 'Gaza City', 'Gaza', '5493064XHAMAS7766', 'Other', 'Other', 'Other', '< $1M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Bashar al-Assad', 'Presidential Palace, Damascus', 'Syria', '5493065XASSAD5544', 'Other', 'Other', 'Other', '$1M - $10M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Mahan Air', 'Mahan Tower, Tehran', 'Iran', '5493066XMAHAN3322', 'Other', 'Fintech / Payments', 'Operating Revenues', '$10M - $100M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('North Korean National Ship', 'Nampo Port', 'North Korea', '5493067XDPRK1100', 'Other', 'Energy / Commodities', 'Operating Revenues', '$1M - $10M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Petroleos de Venezuela, S.A. (PDVSA)', 'Av Libertador, Caracas', 'Venezuela', '5493068XPDVSA9988', 'Corporate', 'Energy / Commodities', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Alisher Usmanov', 'Rublyovksy Highway, Moscow', 'Russia', '5493069XALISHER1122', 'Other', 'Investment Banking', 'Investment Returns', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Fake Institutional Bank', '999 Ghost St, Void City', 'United States', '9999999VOID999999999', 'Bank', 'Investment Banking', 'Other', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Shadow Valley Funds', 'Locked Suite, Cayman', 'Cayman Islands', '0000000SHADOW000000', 'Fund', 'Asset Management', 'Loan / Credit Facility', '$10M - $100M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Zaphod Beeblebrox Exports', 'Magrathea Sect 7', 'Other', '4242424MAGRA42424242', 'Corporate', 'Other', 'Shareholder Capital', '< $1M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Global Phantom Tradings', 'Unknown Warehouse, Mumbai', 'India', 'IND99999PHANTOM0011', 'Broker-Dealer', 'Energy / Commodities', 'Operating Revenues', '$1M - $10M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Invisble Wealth LLC', '101 Nowhere Ln', 'United Kingdom', 'UK99999INVISI0022', 'Corporate', 'Real Estate', 'Operating Revenues', '< $1M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('High Volume Fintech SG', 'Raffles Place, Singapore', 'Singapore', '5493005KJY7UW9K33334', 'Corporate', 'Fintech / Payments', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Middle East Energy Trading', 'Doha Tech Plaza', 'Qatar', '5493067KJY7UH9L33446', 'Corporate', 'Energy / Commodities', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Latin American Mining Corp', 'Santiago Mining Hub', 'Chile', '5493087KJY7UH9N33446', 'Corporate', 'Energy / Commodities', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Crypto Gateway Malta', 'Sliema Blockchain Heights', 'Malta', '5493061KJY7UB9L55670', 'Broker-Dealer', 'Fintech / Payments', 'Operating Revenues', '$100M+', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL),
('Congo Minerals Trust', 'Kinshasa Export Zone', 'DRC', '5493071KJY7UB9M55671', 'Corporate', 'Energy / Commodities', 'Operating Revenues', '$10M - $100M', 'PENDING_REVIEW', NULL, NULL, NULL, NULL, NULL);
"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write("SET client_encoding = 'UTF8';\n" + content)

def fix_verification():
    path = r'd:\learning\aml\db\verification_data.sql'
    header = """SET client_encoding = 'UTF8';
-- KINETIX PLATFORM: Entity Verification Reference Data
-- Mock dataset for testing and verification logic

CREATE TABLE IF NOT EXISTS client_onboarding.entity_verification (
    lei_number CHAR(20) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    entity_type VARCHAR(50) NOT NULL, -- Bank, Broker-Dealer, Fund, Corporate, Other
    registered_address TEXT NOT NULL,
    country VARCHAR(100) NOT NULL,
    ein_number VARCHAR(50),           -- Federal Tax ID (New)
    dba_name VARCHAR(255),            -- Doing Business As (New)
    verification_status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Mock Data (100 Records)
INSERT INTO client_onboarding.entity_verification (lei_number, company_name, entity_type, registered_address, country, ein_number, dba_name) VALUES
"""
    rows = [
        "('5493001KJY7UW9K12345', 'Evergreen Financial Group', 'Bank', '120 Wall Street, New York, NY 10005', 'United States', '12-3456789', 'Evergreen Private Wealth')",
        "('5493002KJY7UW9K67890', 'North Star Asset Management', 'Fund', '10 Collyer Quay, Ocean Financial Centre', 'Singapore', 'SG-99-887766', 'North Star Funds')",
        "('5493003KJY7UW9K11111', 'Riverbank Global Trade', 'Corporate', 'Canary Wharf, London E14 5AB', 'United Kingdom', 'UK-77-665544', 'Riverbank FX')",
        "('5493004KJY7UW9K22222', 'Indus Valley Ventures', 'Broker-Dealer', 'Bandra Kurla Complex, Mumbai, MH 400051', 'India', 'AAACI-1234-A', 'Indus Valley Investments')",
        "('5493005KJY7UW9K33333', 'Desert Oasis Logistics', 'Corporate', 'Sheikh Zayed Road, Dubai', 'United Arab Emirates', 'AE-TRN-1234567', 'Desert Oasis Freight')",
        "('5493006KJY7UW9K44444', 'Alpine Wealth Systems', 'Bank', 'Bahnhofstrasse 45, Zurich', 'Switzerland', NULL, NULL)",
        "('5493007KJY7UW9K55555', 'Sakura Trade Corp', 'Corporate', '1-1-2 Otemachi, Chiyoda-ku, Tokyo', 'Japan', NULL, NULL)",
        "('5493008KJY7UW9K66666', 'Maple Leaf Capital', 'Fund', 'Bay Street, Toronto, ON M5J 2R8', 'Canada', NULL, NULL)",
        "('5493009KJY7UW9K77777', 'Sydney Harbour Trust', 'Bank', 'George Street, Sydney, NSW 2000', 'Australia', NULL, NULL)",
        "('5493010KJY7UW9K88888', 'Frankfurt Deutsche Handels', 'Broker-Dealer', 'Mainzer Landstrasse, Frankfurt', 'Germany', NULL, NULL)",
        "('5493011KJY7UW9K99999', 'Atlas Global Logistics', 'Corporate', '789 Industrial Way, Chicago, IL 60607', 'United States', NULL, NULL)",
        "('5493012KJY7UW9K00000', 'Pacific Rim Equities', 'Fund', 'Marina Bay Financial Centre, Tower 1', 'Singapore', NULL, NULL)",
        "('5493013KJY7UW9K12121', 'Thames River Clearing', 'Bank', 'Lombard Street, London EC3V 9AA', 'United Kingdom', NULL, NULL)",
        "('5493014KJY7UW9K23232', 'Ganges Delta Trading', 'Corporate', 'Salt Lake Sector V, Kolkata, WB 700091', 'India', NULL, NULL)",
        "('5493015KJY7UW9K34343', 'Burj Khalifa Partners', 'Other', 'Emaar Square, Dubai', 'United Arab Emirates', NULL, NULL)",
        "('5493016KJY7UW9K45454', 'Nordic Maritime Trust', 'Corporate', 'Karl Johans gate, Oslo', 'Norway', NULL, NULL)",
        "('5493017KJY7UW9K56565', 'Singapore Sovereign Fund', 'Fund', 'Robinson Road 168', 'Singapore', NULL, NULL)",
        "('5493018KJY7UW9K67676', 'Manhattan Bridge Capital', 'Broker-Dealer', 'DUMBO, Brooklyn, NY 11201', 'United States', NULL, NULL)",
        "('5493019KJY7UW9K78787', 'Highlands Energy Group', 'Corporate', 'Union Street, Aberdeen', 'United Kingdom', NULL, NULL)",
        "('5493020KJY7UW9K89898', 'Bangalore Tech Solutions', 'Corporate', 'Electronic City, Bangalore, KA 560100', 'India', NULL, NULL)",
        "('5493021KJY7UW9K90909', 'Gold Coast Real Estate', 'Other', 'Surfers Paradise, QLD 4217', 'Australia', NULL, NULL)",
        "('5493022KJY7UW9K01010', 'Parisian Luxury Holdings', 'Corporate', 'Avenue Montaigne, Paris', 'France', NULL, NULL)",
        "('5493023KJY7UW9K11223', 'Hong Kong Dragon Bank', 'Bank', 'Queen''s Road Central', 'Hong Kong', NULL, NULL)",
        "('5493024KJY7UW9K44556', 'Rhine Valley Biotech', 'Corporate', 'Ludwigshafen', 'Germany', NULL, NULL)",
        "('5493025KJY7UW9L77889', 'Silicon Alley Ventures', 'Fund', 'Palo Alto, CA 94301', 'United States', NULL, NULL)",
        "('5493026KJY7UW9M00112', 'Vatican Heritage Trust', 'Other', 'Piazza San Pietro', 'Vatican City', NULL, NULL)",
        "('5493027KJY7UW9N33445', 'Dublin Tech Hub', 'Corporate', 'Grand Canal Dock, Dublin', 'Ireland', NULL, NULL)",
        "('5493028KJY7UW9O66778', 'Cape Town Safari Group', 'Other', 'V&A Waterfront', 'South Africa', NULL, NULL)",
        "('5493029KJY7UW9P99001', 'Rio Carnival Exports', 'Corporate', 'Copacabana, Rio de Janeiro', 'Brazil', NULL, NULL)",
        "('5493030KJY7UW9Q22334', 'Seoul Galaxy Tech', 'Corporate', 'Gangnam-gu, Seoul', 'South Korea', NULL, NULL)",
        "('5493031KJY7UW9R55667', 'Stockholm Green Energy', 'Corporate', 'Norrmalm, Stockholm', 'Sweden', NULL, NULL)",
        "('5493032KJY7UW9S88990', 'Mumbai Gold Exchange', 'Broker-Dealer', 'Zaveri Bazaar, Mumbai', 'India', NULL, NULL)",
        "('5493033KJY7UW9T11221', 'London Fog Insurance', 'Bank', 'The Gherkin, London', 'United Kingdom', NULL, NULL)",
        "('5493034KJY7UW9U44552', 'Texas Oil & Gas', 'Corporate', 'Houston Tech Corridor', 'United States', NULL, NULL)",
        "('5493035KJY7UW9V77883', 'Dubai Pearl Realty', 'Other', 'Palm Jumeirah', 'United Arab Emirates', NULL, NULL)",
        "('5493036KJY7UW9W00114', 'Vienna Classical Arts', 'Other', 'Ringstrasse, Vienna', 'Austria', NULL, NULL)",
        "('5493037KJY7UW9X33445', 'Brussels Policy Hub', 'Other', 'European Quarter', 'Belgium', NULL, NULL)",
        "('5493038KJY7UW9Y66776', 'Amsterdam Canal Trading', 'Corporate', 'Herengracht, Amsterdam', 'Netherlands', NULL, NULL)",
        "('5493039KJY7UW9Z99007', 'Beijing Silk Road', 'Corporate', 'Wangfujing, Beijing', 'China', NULL, NULL)",
        "('5493040KJA7UW9A22338', 'Auckland Kiwi Exports', 'Corporate', 'Queen Street, Auckland', 'New Zealand', NULL, NULL)",
        "('6493041KJY7UW9B55669', 'Madrid Solar Power', 'Corporate', 'Paseo de la Castellana', 'Spain', NULL, NULL)",
        "('7493042KJY7UW9C88990', 'Lisbon Port Authority', 'Other', 'Ribeira Das Naus', 'Portugal', NULL, NULL)",
        "('8493043KJY7UW9D11221', 'Athens Olympic Assets', 'Other', 'Syntagma Square', 'Greece', NULL, NULL)",
        "('9493044KJY7UW9E44552', 'Rome Coliseum Tours', 'Other', 'Viale dei Fori Imperiali', 'Italy', NULL, NULL)",
        "('0493045KJY7UW9F77883', 'Prague Castle Trust', 'Other', 'Hradčany', 'Czech Republic', NULL, NULL)",
        "('1493046KJY7UW9G00114', 'Warsaw Iron Works', 'Corporate', 'Centrum, Warsaw', 'Poland', NULL, NULL)",
        "('2493047KJY7UW9H33445', 'Budapest River Cruises', 'Other', 'Danube Promenade', 'Hungary', NULL, NULL)",
        "('3493048KJY7UW9I66776', 'Copenhagen Design Co', 'Corporate', 'Nyhavn', 'Denmark', NULL, NULL)",
        "('4493049KJY7UW9J99007', 'Helsinki Nokia Tower', 'Corporate', 'Espoo', 'Finland', NULL, NULL)",
        "('5493050KJY7UA9K22338', 'Oslo Fjord Fisheries', 'Corporate', 'Aker Brygge', 'Norway', NULL, NULL)",
        "('5493051KJY7UB9K55669', 'Luxembourg Private Bank', 'Bank', 'Kirchberg Plateau', 'Luxembourg', NULL, NULL)",
        "('5493052KJY7UC9K88990', 'Monaco Yacht Services', 'Other', 'Port Hercules', 'Monaco', NULL, NULL)",
        "('5493053KJY7UD9K11221', 'Geneva Private Wealth', 'Bank', 'Quai du Mont-Blanc', 'Switzerland', NULL, NULL)",
        "('5493054KJY7UE9K44552', 'Zurich Insurance Group', 'Bank', 'Mythenquai', 'Switzerland', NULL, NULL)",
        "('5493055KJY7UF9K77883', 'Jersey Offshore Trust', 'Fund', 'St Helier', 'Jersey', NULL, NULL)",
        "('5493056KJY7UG9K00114', 'Cayman Islands Fund', 'Fund', 'George Town', 'Cayman Islands', NULL, NULL)",
        "('5493057KJY7UH9K33445', 'Bermuda Reinsurance', 'Corporate', 'Hamilton', 'Bermuda', NULL, NULL)",
        "('5493058KJY7UI9K66776', 'British Virgin Isles Co', 'Corporate', 'Road Town', 'British Virgin Islands', NULL, NULL)",
        "('5493059KJY7UJ9K99007', 'Isle of Man Gaming', 'Corporate', 'Douglas', 'Isle of Man', NULL, NULL)",
        "('5493060KJY7UA9L22338', 'Gibraltar Rock Finance', 'Bank', 'Main Street', 'Gibraltar', NULL, NULL)",
        "('5493061KJY7UB9L55669', 'Malta Crypto Hub', 'Broker-Dealer', 'Sliema', 'Malta', NULL, NULL)",
        "('5493062KJY7UC9L88990', 'Cyprus Alpha Trading', 'Broker-Dealer', 'Limassol', 'Cyprus', NULL, NULL)",
        "('5493063KJY7UD9L11221', 'Tel Aviv Tech Ventures', 'Fund', 'Rothschild Boulevard', 'Israel', NULL, NULL)",
        "('5493064KJY7UE9L44552', 'Istanbul Bazaar Corp', 'Corporate', 'Grand Bazaar Area', 'Turkey', NULL, NULL)",
        "('5493065KJY7UF9L77883', 'Cairo Nile Exports', 'Corporate', 'Tahrir Square Business Hub', 'Egypt', NULL, NULL)",
        "('5493066KJY7UG9L00114', 'Riyadh Desert Energy', 'Corporate', 'Kingdom Centre', 'Saudi Arabia', NULL, NULL)",
        "('5493067KJY7UH9L33445', 'Doha Natural Gas', 'Corporate', 'West Bay', 'Qatar', NULL, NULL)",
        "('5493068KJY7UI9L66776', 'Kuwait City Petroleum', 'Corporate', 'Al Hamra Tower', 'Kuwait', NULL, NULL)",
        "('5493069KJY7UJ9L99007', 'Bahrain Financial Harbor', 'Bank', 'Bahrain Bay', 'Bahrain', NULL, NULL)",
        "('5493070KJY7UA9M22338', 'Muscat Royal Trading', 'Corporate', 'Muttrah Corniche', 'Oman', NULL, NULL)",
        "('5493071KJY7UB9M55669', 'Johannesburg Mining', 'Corporate', 'Sandton Financial District', 'South Africa', NULL, NULL)",
        "('5493072KJY7UC9M88990', 'Nairobi M-Pesa Hub', 'Bank', 'Westlands', 'Kenya', NULL, NULL)",
        "('5493073KJY7UD9M11221', 'Lagos Atlantic Tech', 'Corporate', 'Victoria Island', 'Nigeria', NULL, NULL)",
        "('5493074KJY7UE9M44552', 'Casablanca Finance City', 'Fund', 'Anfa District', 'Morocco', NULL, NULL)",
        "('5493075KJY7UF9M77883', 'Mauritius Offshore Bank', 'Bank', 'Port Louis', 'Mauritius', NULL, NULL)",
        "('5493076KJY7UG9M00114', 'Seychelles Azure Assets', 'Fund', 'Victoria', 'Seychelles', NULL, NULL)",
        "('5493077KJY7UH9M33445', 'Singapore Star Bulk', 'Corporate', 'Jurong West', 'Singapore', NULL, NULL)",
        "('5493078KJY7UI9M66776', 'Kuala Lumpur Petronas', 'Corporate', 'KLCC', 'Malaysia', NULL, NULL)",
        "('5493079KJY7UJ9M99007', 'Bangkok River Trade', 'Corporate', 'Sathorn District', 'Thailand', NULL, NULL)",
        "('5493080KJY7UA9N22338', 'Jakarta Archipelago Inc', 'Corporate', 'Sudirman Central Business', 'Indonesia', NULL, NULL)",
        "('5493081KJY7UB9N55669', 'Manila Bay Ventures', 'Fund', 'Makati City', 'Philippines', NULL, NULL)",
        "('5493082KJY7UC9N88990', 'Hanoi Red River Trading', 'Corporate', 'Hoan Kiem District', 'Vietnam', NULL, NULL)",
        "('5493083KJY7UD9N11221', 'Taipei 101 Capital', 'Broker-Dealer', 'Xinyi District', 'Taiwan', 'TW-88-9900', 'Taipei Investments')",
        "('5493084KJY7UE9N44552', 'Moscow Red Square Bank', 'Bank', 'Presnenskaya Embankment', 'Russia', 'RU-INN-7705505', 'Red Square Ops')",
        "('5493085KJY7UF9N77883', 'Sao Paulo Coffee Corp', 'Corporate', 'Avenida Paulista', 'Brazil', NULL, NULL)",
        "('5493086KJY7UG9N00114', 'Buenos Aires Tango Fund', 'Fund', 'Puerto Madero', 'Argentina', NULL, NULL)",
        "('5493087KJY7UH9N33445', 'Santiago Andes Mining', 'Corporate', 'Providencia', 'Chile', NULL, NULL)",
        "('5493088KJY7UI9N66776', 'Lima Incan Gold', 'Corporate', 'Miraflores', 'Peru', NULL, NULL)",
        "('5493089KJY7UJ9N99007', 'Bogota Coffee Exports', 'Corporate', 'Calle 72 Center', 'Colombia', NULL, NULL)",
        "('5493090KJY7UA9O22338', 'Mexico City Reforma Bank', 'Bank', 'Paseo de la Reforma', 'Mexico', NULL, NULL)",
        "('5493091KJY7UB9O55669', 'Vancouver Peak Resources', 'Corporate', 'Coal Harbour', 'Canada', NULL, NULL)",
        "('5493092KJY7UC9O88990', 'Montreal Biotech Labs', 'Corporate', 'Downtown Montreal', 'Canada', NULL, NULL)",
        "('5493093KJY7UD9O11221', 'Chicago Windy City Broker', 'Broker-Dealer', 'The Loop', 'United States', NULL, NULL)",
        "('5493094KJY7UF9O77883', 'Miami Beach Real Estate', 'Other', 'South Beach', 'United States', NULL, NULL)",
        "('5493095KJY7UF9O77883', 'Atlanta Peach Assets', 'Fund', 'Buckhead', 'United States', NULL, NULL)",
        "('5493096KJY7UG9O00114', 'Seattle Emerald Tech', 'Corporate', 'South Lake Union', 'United States', NULL, NULL)",
        "('5493097KJY7UH9O33445', 'Denver Mountain Peak', 'Corporate', 'Downtown Denver', 'United States', NULL, NULL)",
        "('5493098KJY7UI9O66776', 'Salt Lake Salt Trading', 'Corporate', 'Sugar House', 'United States', NULL, NULL)",
        "('5493099KJY7UJ9O99007', 'Phoenix Sun Solar', 'Corporate', 'Biltmore Area', 'United States', NULL, NULL)",
        "('5493010KJY7UA9P22340', 'Las Vegas Neon Lights', 'Other', 'The Strip', 'United States', NULL, NULL)"
    ]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write(",\n".join(rows) + ";\n")

if __name__ == "__main__":
    fix_sanctions()
    fix_aml()
    fix_verification()
    print("SQL files fixed successfully.")
