-- KINETIX PLATFORM: OFAC-Style Sanctions Reference Data
-- Mock dataset with Entity Addresses for compliance screening

CREATE TABLE IF NOT EXISTS sanctions_list (
    id SERIAL PRIMARY KEY,
    entity_name VARCHAR(255) NOT NULL,
    entity_type VARCHAR(50) NOT NULL, -- INDIVIDUAL, ENTITY, VESSEL, AIRCRAFT
    program VARCHAR(100) NOT NULL,    -- e.g., RUSSIA, IRAN, SDGT
    list_type VARCHAR(50) NOT NULL,   -- SDN, NON-SDN
    country VARCHAR(100),
    entity_address TEXT,              -- Physical or registered address
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Mock Data (200 Records)
INSERT INTO sanctions_list (entity_name, entity_type, program, list_type, country, entity_address, remarks) VALUES
-- RUSSIA (60 Records)
('VTB Bank PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '12 Presnenskaya Naberezhnaya, Moscow', 'Major state-owned bank'),
('Sberbank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '19 Vavilova St, Moscow', 'Russian financial services giant'),
('Gazprombank PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '16 Nametkina St, Moscow', 'Energy sector financial arm'),
('Alfa-Bank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '27 Kalanchyovskaya St, Moscow', 'Private commercial bank'),
('Promsvyazbank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '10 Smirnovskaya St, Moscow', 'Defense sector bank'),
('Alisher Usmanov', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Rublyovksy Highway, Moscow', 'Oligarch, metals and tech'),
('Roman Abramovich', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Tsvetnoy Blvd, Moscow', 'Prominent businessman'),
('Igor Sechin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Sofiyskaya Naberezhnaya, Moscow', 'CEO of Rosneft'),
('Alexey Miller', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Nametkina St, Moscow', 'CEO of Gazprom'),
('Gennady Timchenko', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Geneva, Switzerland (Primary Res)', 'Volga Group founder'),
('Rosneft Oil Company', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '26/1 Sofiyskaya Naberezhnaya, Moscow', 'State oil major'),
('Gazprom PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '16 Nametkina St, Moscow', 'State gas giant'),
('Rostec', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '24 Usacheva St, Moscow', 'State defense conglomerate'),
('United Shipbuilding Corporation', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '11 Maroseyka St, Moscow', 'Naval construction'),
('Sukhoi Aviation', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '23B Polikarpov St, Moscow', 'Aircraft manufacturer'),
('Kalashnikov Concern', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '3 Deryabin Prospekt, Izhevsk', 'Small arms manufacturer'),
('Bank Rossiya', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '2 Rastrelli Square, St. Petersburg', 'St. Petersburg based bank'),
('SMP Bank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Sadovnicheskaya St, Moscow', 'Rotenberg-controlled bank'),
('Uralvagonzavod', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '28 Vostochnoye Highway, Nizhny Tagil', 'Tank manufacturer'),
('Wagner Group', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Molkino, Krasnodar Krai', 'Private military company'),
('Yevgeny Prigozhin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'St. Petersburg, Russia', 'Wagner founder'),
('Sergei Roldugin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Mariinsky Theatre, St. Petersburg', 'Cellist, associate of leadership'),
('Arkady Rotenberg', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', 'Infrastructure tycoon'),
('Boris Rotenberg', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', 'Co-owner of SMP Bank'),
('Nikolai Patrushev', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Kremlin, Moscow', 'Security Council Secretary'),
('Alexander Bortnikov', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Lubyanka Sq, Moscow', 'FSB Director'),
('Sergei Naryshkin', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Yasenovo, Moscow', 'SVR Director'),
('Yuri Kovalchuk', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'St. Petersburg, Russia', 'Bank Rossiya chairman'),
('Oleg Deripaska', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'London/Moscow', 'En+ Group founder'),
('Viktor Vekselberg', 'INDIVIDUAL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', 'Renova Group owner'),
('United Energy Systems', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Kitaigorodsky Proyezd, Moscow', 'Electricity grids'),
('Aeroflot PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Arbat St, Moscow', 'Flag carrier'),
('Russian Railways (RZD)', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Novaya Basmannaya, Moscow', 'State rail operator'),
('Transneft', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Polyanka St, Moscow', 'Oil pipeline monopoly'),
('Alrosa PJSC', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Mirny, Sakha Republic', 'Diamond mining major'),
('Sovcombank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Kostroma, Russia', 'Universal commercial bank'),
('Novatek PAO', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Tarkosale, Yamalo-Nenets', 'LNG producer'),
('Norilsk Nickel', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '1st Krasnogvardeyskiy Proyezd, Moscow', 'Nickel and palladium producer'),
('Militia Forces of DNR', 'ENTITY', 'UKRAINE-EO13660', 'SDN', 'Ukraine/Russia', 'Donetsk, Ukraine', 'Armed group in East Ukraine'),
('Militia Forces of LNR', 'ENTITY', 'UKRAINE-EO13660', 'SDN', 'Ukraine/Russia', 'Luhansk, Ukraine', 'Armed group in East Ukraine'),
('Zelenograd Scientific Center', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Georgievsky Prospekt, Zelenograd', 'Microelectronics research'),
('Baikal Electronics', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', 'Processor designer'),
('Mikron', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', '10 Akademika Valli St, Zelenograd', 'Semiconductor manufacturer'),
('MCST', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Nagatinskaya St, Moscow', 'Elbrus processor developer'),
('T-Platforms', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moscow, Russia', 'Supercomputer manufacturer'),
('Radio-Electronic Technologies (KRET)', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Goncharnaya St, Moscow', 'Avionics manufacturer'),
('High Precision Systems', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Leningradsky Prospekt, Moscow', 'Missile systems'),
('Tactical Missiles Corporation', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Korolev, Moscow Oblast', 'Weapon systems'),
('Russian Direct Investment Fund (RDIF)', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Vozdvizhenka St, Moscow', 'Sovereign wealth fund'),
('VEB.RF', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Academician Sakharov Ave, Moscow', 'Development bank'),
('Novikombank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Polyanka St, Moscow', 'Rostec-owned bank'),
('Bank Otkritie', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Letnikovskaya St, Moscow', 'Major retail bank'),
('Credit Bank of Moscow', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Lukov Ln, Moscow', 'Commercial bank'),
('Rosselkhozbank', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Olkhovskaya St, Moscow', 'Agricultural bank'),
('Stroytransgaz', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Arbat St, Moscow', 'Infrastructure construction'),
('Stroygazmontazh', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Vavilova St, Moscow', 'Energy construction'),
('Mostotrest', 'ENTITY', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Barklaya St, Moscow', 'Bridge construction'),
('Uran-9', 'VESSEL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Moored at Sevastopol', 'Autonomous naval system'),
('Admiral Kuznetsov', 'VESSEL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Severomorsk Naval Base', 'Aircraft carrier'),
('Moskva', 'VESSEL', 'RUSSIA-EO14024', 'SDN', 'Russia', 'Sunk (formerly Sevastopol)', 'Missile cruiser'),

-- IRAN (40 Records)
('Central Bank of Iran', 'ENTITY', 'IRAN', 'SDN', 'Iran', '144 Mirdamad Blvd, Tehran', 'Central financial regulator'),
('Bank Melli Iran', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Ferdowsi Ave, Tehran', 'Commercial bank'),
('Bank Mellat', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Valiasr Ave, Tehran', 'Commercial bank'),
('Bank Sepah', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Saeid Sq, Tehran', 'Military-linked bank'),
('Parsian Bank', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Argentina Sq, Tehran', 'Private bank'),
('Pasargad Bank', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Mirdamad Blvd, Tehran', 'Private bank'),
('Islamic Revolutionary Guard Corps (IRGC)', 'ENTITY', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran (Multiple HQ)', 'Elite military force'),
('Quds Force', 'ENTITY', 'SDGT', 'SDN', 'Iran', 'Tehran, Iran', 'IRGC external operations'),
('Ebrahim Raisi', 'INDIVIDUAL', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', 'Political leadership'),
('Ali Khamenei', 'INDIVIDUAL', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', 'Supreme Leader'),
('Mohammad Javad Zarif', 'INDIVIDUAL', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', 'Former Foreign Minister'),
('Qasem Soleimani', 'INDIVIDUAL', 'SDGT', 'SDN', 'Iran', 'Kerman, Iran (Gravesite)', 'Deceased Quds Force commander'),
('National Iranian Oil Company (NIOC)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Taleghani Ave, Tehran', 'State oil company'),
('National Iranian Tanker Company (NITC)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Atefi St, Tehran', 'Oil shipping'),
('Islamic Republic of Iran Shipping Lines (IRISL)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Aseman Tower, Tehran', 'National shipping line'),
('Atomic Energy Organization of Iran (AEOI)', 'ENTITY', 'NPWMD', 'SDN', 'Iran', 'Kargar Ave, Tehran', 'Nuclear program lead'),
('Mahan Air', 'ENTITY', 'SDGT', 'SDN', 'Iran', 'Mahan Tower, Tehran', 'Commercial airline'),
('Iran Air', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Mehrabad Airport, Tehran', 'Flag carrier'),
('Petrochemical Commercial Company (PCC)', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Vanak Sq, Tehran', 'Petrochemical exports'),
('Persia Cargo', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kish Island, Iran', 'Logistics'),
('Abadan Refinery', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Abadan, Khuzestan', 'Oil refining'),
('Kharg Island Loading', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kharg Island, Persian Gulf', 'Strategic oil port'),
('Iranian Offshore Oil Company', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', 'Offshore production'),
('Mapna Group', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Mirdamad Blvd, Tehran', 'Energy infrastructure'),
('Saipa Motor', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kilometer 15 Karaj Rd, Tehran', 'Automotive manufacturer'),
('Iran Khodro', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kilometer 14 Karaj Rd, Tehran', 'Automotive manufacturer'),
('Shahid Hemmat Industrial Group', 'ENTITY', 'NPWMD', 'SDN', 'Iran', 'Parchin, Iran', 'Ballistic missile program'),
('Shahid Bakeri Industrial Group', 'ENTITY', 'NPWMD', 'SDN', 'Iran', 'Khojir, Iran', 'Ballistic missile program'),
('Defense Industries Organization', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Pasdaran St, Tehran', 'Military production'),
('Khatam al-Anbiya', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', 'IRGC construction arm'),
('Execution of Imam Khomeini''s Order (EIKO)', 'ENTITY', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', 'Parastatal conglomerate'),
('Mostazafan Foundation', 'ENTITY', 'IRAN-HR', 'SDN', 'Iran', 'Tehran, Iran', 'Bonyad conglomerate'),
('Bank Saderat Iran', 'ENTITY', 'SDGT', 'SDN', 'Iran', 'Somayeh St, Tehran', 'Involved in terrorism financing'),
('Future Bank B.S.C.', 'ENTITY', 'IRAN', 'SDN', 'Bahrain/Iran', 'Manama, Bahrain', 'Joint venture bank'),
('Persia International Bank PLC', 'ENTITY', 'IRAN', 'SDN', 'UK/Iran', '6-8 Lothbury, London', 'London-based subsidiary'),
('EIKO Wealth Management', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Tehran, Iran', 'Financial arm'),
('Saman Bank', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Valiasr Ave, Tehran', 'Commercial bank'),
('Tehran Stock Exchange', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Hafez St, Tehran', 'Capital markets'),
('Kish Protection and Indemnity', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Kish Island, Iran', 'Maritime insurance'),
('Bimeh Iran', 'ENTITY', 'IRAN', 'SDN', 'Iran', 'Fatemi St, Tehran', 'State insurance'),

-- NORTH KOREA (30 Records)
('Foreign Trade Bank of DPRK', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Jungsong-dong, Pyongyang', 'Main foreign exchange bank'),
('Korea Kwangson Banking Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Financial operations'),
('Kim Jong Un', 'INDIVIDUAL', 'DPRK', 'SDN', 'North Korea', 'Ryongsong Residence, Pyongyang', 'Supreme Leader'),
('Kim Yo Jong', 'INDIVIDUAL', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Political leadership'),
('Lazarus Group', 'ENTITY', 'CYBER-DPRK', 'SDN', 'North Korea', 'Potonggang District, Pyongyang', 'Cyber warfare unit'),
('Koryo Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'State bank'),
('Daedong Credit Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Joint venture bank'),
('Mansudae Overseas Projects', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Overseas construction'),
('Air Koryo', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Sunan Airport, Pyongyang', 'State airline'),
('Kaesong Industrial Complex', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Kaesong, NK', 'Economic zone'),
('Namchongang Trading Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Nuclear procurement'),
('Korea Mining Development Trading Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Arms exports'),
('Choson Expo', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Software development'),
('Ryugyong Hotel Trust', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Hospitality'),
('DPRK Merchant Marine', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Shipping coordination'),
('Mu Bong 1', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Anchored at Nampo', 'Cargo ship'),
('Hui Chon', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Nampo Port', 'Container vessel'),
('Jang Ja San Ho', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Wonsan Port', 'Bulk carrier'),
('O Ryong', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Hungnam Port', 'Oil tanker'),
('Po Thong Gang', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Pyongyang Port', 'General cargo'),
('Ryong Gun Bong', 'VESSEL', 'DPRK', 'SDN', 'North Korea', 'Nampo Port', 'General cargo'),
('Tangun Trading Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Advanced technology'),
('Green Pine Associated Corp', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Wonsan, NK', 'Maritime intelligence'),
('Lab 110', 'ENTITY', 'CYBER-DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Reconnaissance General Bureau'),
('Chosun United Development Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Capital investment'),
('Amroggang Development Bank', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Currency operations'),
('Korea Computer Center', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'IT development'),
('Red Star OS', 'ENTITY', 'CYBER-DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'State operating system'),
('Pan Systems Pyongyang', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Pyongyang, NK', 'Electronics trade'),
('Haegeumgang Resort', 'ENTITY', 'DPRK', 'SDN', 'North Korea', 'Mt Kumgang', 'Tourism assets'),

-- SYRIA (20 Records)
('Central Bank of Syria', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Altajhiz St, Damascus', 'Monetary authority'),
('Commercial Bank of Syria', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Yousef Al-Azmeh Sq, Damascus', 'Largest state bank'),
('Bashar al-Assad', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Presidential Palace, Damascus', 'President'),
('Asma al-Assad', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', 'First Lady'),
('Syrian Arab Airlines', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus Int Airport', 'Flag carrier'),
('Cham Wings Airlines', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus Tower Bldg', 'Private airline'),
('Syrian Petroleum Company', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Dummar, Damascus', 'State energy'),
('Mahrukat', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', 'Fuel distribution'),
('Baniyas Refinery', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Baniyas, Tartus', 'Oil refinement'),
('Homs Refinery', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Homs, Syria', 'Oil refinement'),
('Military Intelligence Directorate', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Kafar Souseh, Damascus', 'Security apparatus'),
('Tiger Forces', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Latakia, Syria', 'Elite military unit'),
('Rami Makhlouf', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', 'Tycoon, associate of leadership'),
('Al-Watan Newspaper', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', 'State-linked media'),
('Syrian Scientific Studies and Research Center', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Barzah, Damascus', 'Chemical weapons research'),
('Mediterranean Shipping Agency', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Tartus Port, Syria', 'Maritime logistics'),
('Latakia Port Authority', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Latakia Port, Syria', 'Major seaport'),
('Tartus Port Management', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Tartus Port, Syria', 'Strategic port'),
('Maher al-Assad', 'INDIVIDUAL', 'SYRIA', 'SDN', 'Syria', 'Damascus, Syria', 'Military commander'),
('Syriatel', 'ENTITY', 'SYRIA', 'SDN', 'Syria', 'Mazzeh Highway, Damascus', 'Telecom provider'),

-- VENEZUELA (20 Records)
('Petroleos de Venezuela, S.A. (PDVSA)', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Libertador, Caracas', 'State oil company'),
('Nicolas Maduro', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Palacio de Miraflores, Caracas', 'President'),
('Diosdado Cabello', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Caracas, Venezuela', 'Political leadership'),
('Cilia Flores', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Caracas, Venezuela', 'Political leadership'),
('Delcy Rodriguez', 'INDIVIDUAL', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Caracas, Venezuela', 'Vice President'),
('Tareck El Aissami', 'INDIVIDUAL', 'NARCO-VENEZUELA', 'SDN', 'Venezuela', 'Caracas, Venezuela', 'Former Petroleum Minister'),
('Central Bank of Venezuela', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Urdaneta, Caracas', 'Monetary authority'),
('BANDES', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Universidad, Caracas', 'Economic development bank'),
('Banco de Venezuela', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Av Universidad, Caracas', 'State-owned bank'),
('CVG Fundicion', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Puerto Ordaz, Bolivar', 'Gold/Mining sector'),
('Minerven', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'El Callao, Bolivar', 'State gold mining'),
('Alex Saab', 'INDIVIDUAL', 'VENEZUELA-EO13850', 'SDN', 'Colombia/Venezuela', 'Barranquilla, Colombia', 'Corruption/Money laundering'),
('Citgo Petroleum (US blocked)', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'USA/Venezuela', '1293 Eldridge Pkwy, Houston, TX', 'Refining subsidiary'),
('Conviasa', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Maiquetia Airport, Vargas', 'State airline'),
('SEBIN', 'ENTITY', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'El Helicoide, Caracas', 'Intelligence agency'),
('DGCIM', 'ENTITY', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Boleita, Caracas', 'Military counterintelligence'),
('National Electoral Council (CNE)', 'ENTITY', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Plaza Caracas, Caracas', 'Electoral authority'),
('Supreme Tribunal of Justice (TSJ)', 'ENTITY', 'VENEZUELA-EO13692', 'SDN', 'Venezuela', 'Av Baralt, Caracas', 'Judiciary'),
('Pante Pente', 'VESSEL', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Jose Terminal, Anzoategui', 'Oil tanker'),
('Sandino', 'VESSEL', 'VENEZUELA-EO13850', 'SDN', 'Venezuela', 'Puerto La Cruz', 'Oil tanker'),

-- OTHERS: Belarus, Cuba, Yemen, Myanmar, etc. (30 Records)
('Alexander Lukashenko', 'INDIVIDUAL', 'BELARUS', 'SDN', 'Belarus', 'Independence Palace, Minsk', 'President'),
('Belaruskali', 'ENTITY', 'BELARUS', 'SDN', 'Belarus', 'Soligorsk, Belarus', 'Potash producer'),
('Belintertrans', 'ENTITY', 'BELARUS', 'SDN', 'Belarus', 'Oktyabrskaya St, Minsk', 'Logistics'),
('Cubaexport', 'ENTITY', 'CUBA', 'SDN', 'Cuba', 'Calle 23, Havana', 'State export agency'),
('Banco Central de Cuba', 'ENTITY', 'CUBA', 'SDN', 'Cuba', 'Havana, Cuba', 'Central bank'),
('Miguel Diaz-Canel', 'INDIVIDUAL', 'CUBA', 'SDN', 'Cuba', 'Palace of the Revolution, Havana', 'President'),
('Houthis / Ansar Allah', 'ENTITY', 'SDGT', 'SDN', 'Yemen', 'Sana''a, Yemen', 'Armed group'),
('Abdul-Malik al-Houthi', 'INDIVIDUAL', 'SDGT', 'SDN', 'Yemen', 'Saada, Yemen', 'Houthi leader'),
('Myanmar Economic Holdings', 'ENTITY', 'MYANMAR-EO14014', 'SDN', 'Myanmar', 'Nay Pyi Taw, Myanmar', 'Military conglomerate'),
('Min Aung Hlaing', 'INDIVIDUAL', 'MYANMAR-EO14014', 'SDN', 'Myanmar', 'Nay Pyi Taw, Myanmar', 'Military leader'),
('Zimbabwe Mining Development Corp', 'ENTITY', 'ZIMBABWE', 'SDN', 'Zimbabwe', 'Harare, Zimbabwe', 'Mineral extraction'),
('Emmerson Mnangagwa', 'INDIVIDUAL', 'ZIMBABWE', 'SDN', 'Zimbabwe', 'State House, Harare', 'President'),
('Hezbollah', 'ENTITY', 'SDGT', 'SDN', 'Lebanon', 'Dahieh, Beirut', 'Armed group / Political party'),
('Hassan Nasrallah', 'INDIVIDUAL', 'SDGT', 'SDN', 'Lebanon', 'Beirut, Lebanon', 'Hezbollah Secretary General'),
('Al-Shabaab', 'ENTITY', 'SDGT', 'SDN', 'Somalia', 'Jilib, Somalia', 'Terrorist group'),
('Cartel de Jalisco Nueva Generacion', 'ENTITY', 'NARCO', 'SDN', 'Mexico', 'Jalisco, Mexico', 'Drug cartel'),
('El Mencho', 'INDIVIDUAL', 'NARCO', 'SDN', 'Mexico', 'Unknown, Mexico', 'Cartel leader'),
('Sinatra Oil Tanker', 'VESSEL', 'SDGT', 'SDN', 'Panama/Iran', 'Persian Gulf', 'Oil transport for sanctioned groups'),
('Air Zimbabwe (Gated)', 'ENTITY', 'ZIMBABWE', 'SDN', 'Zimbabwe', 'Harare Airport', 'Aviation'),
('Belarusian Oil Co', 'ENTITY', 'BELARUS', 'SDN', 'Belarus', 'Mozyr, Belarus', 'Oil trade'),
('Hamas', 'ENTITY', 'SDGT', 'SDN', 'Gaza', 'Gaza City', 'Terrorist group'),
('Ismail Haniyeh', 'INDIVIDUAL', 'SDGT', 'SDN', 'Gaza/Qatar', 'Doha, Qatar', 'Political leader'),
('Islamic State (ISIS)', 'ENTITY', 'SDGT', 'SDN', 'Global', 'Varies (Syria/Iraq)', 'Terrorist organization'),
('Al-Qaeda', 'ENTITY', 'SDGT', 'SDN', 'Global', 'Varies (Pakistan/Yemen)', 'Terrorist organization'),
('Taliban', 'ENTITY', 'SDGT', 'SDN', 'Afghanistan', 'Kabul, Afghanistan', 'Governing group'),
('Haibatullah Akhundzada', 'INDIVIDUAL', 'SDGT', 'SDN', 'Afghanistan', 'Kandahar, Afghanistan', 'Taliban leader'),
('Sudan People''s Liberation Movement', 'ENTITY', 'SUDAN-EO13664', 'SDN', 'South Sudan', 'Juba, South Sudan', 'Armed conflict party'),
('Fuerzas Armadas Revolucionarias de Colombia', 'ENTITY', 'SDGT', 'SDN', 'Colombia', 'Varies (Border regions)', 'FARC dissident groups'),
('Los Zetas', 'ENTITY', 'NARCO', 'SDN', 'Mexico', 'Tamaulipas, Mexico', 'Criminal organization'),
('Sinaloa Cartel', 'ENTITY', 'NARCO', 'SDN', 'Mexico', 'Sinaloa, Mexico', 'Criminal organization');
